### PR TITLE
Add parameters to ListIssues call

### PR DESCRIPTION
**Pull request by marcoregueira**
Added parameters to ListIssues call. Added class IssueSearchParameters. 

This works for me but maybe the right way would be use getpaginatedresults.

Related to #39

### CODE REVIEW

**Comment by MitjaBezensek** [comment]
I'm on my vacation and don't have access to a computer. I'll take a look at this as soon as I come back.

**Comment by MitjaBezensek** [comment]
Sorry for a late reply. I looked at the PR and it seems good 👍 
The only thing I noticed is the braces format. The project is using the opening brace on the same line (and not in a new line like the classic c# formatting - will probably change this in the future).

So if you could just please reformat the changes to be consistent with the existing style that would be great. I'll then merge the PR and make a new NuGet package.

**Comment by xrisdoc** [comment]
I have a need to be able to return more than the first 15 issues and this pull request seems to do just that. Pretty much exactly what I'm looking for. So, before I go ahead an implement my own solution, I am just wanting to check if this pull request will be merged any time soon?

**Comment by MitjaBezensek** [comment]
I'll take a look at this during the weekend. Seems fine, so I'll probably just reformat it and merge it.

**Comment by MitjaBezensek** [comment]
@xrisdoc I have reformatted the code and merged it. The NuGet package should be online anytime now.

**Pull request merged**
