### PR TITLE
Add support for the "clone" link type

### PR DESCRIPTION
**Pull request by adamkarl-zywave**
- Update to the latest RestSharp
- Update to the latest json.net
- Add support for the "clone" link type

### CODE REVIEW

**Comment by MitjaBezensek** [comment]
I had to fix the AppVeyor build, it was getting stuck due to the NUnit. But it seems that something is wrong with assembly references:
https://ci.appveyor.com/project/MitjaBezenek/sharpbucket/build/0.2.0.105

With the updated versions of libraries it does not build any longer. I'm not sure why this is happening, might be some caching issue on AppVeyor. Do you maybe have any clues what might be causing this? I might find some time to look into this tomorrow.

Next time please separate different changes into different PRs (adding clone link type and updating to the newest libraries are two non related changes).

**Comment by adamkarl-zywave** [comment]
I see the build issue.  I did not commit the packages folder.  You can have AppVeyor run Nuget Restore by adding a pre-build script "nuget restore" as shown in the article below.  I did this myself and the project now builds.  My tests are still failing on AppVeyor but I think thats some special environment variable setup you've got going?
http://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore

**Comment by adamkarl-zywave** [comment]
Confirmed.  I was able to get AppVeyor to build my fork after adding nuget restore and the 3 environment variables needed for unit testing.

**Comment by MitjaBezensek** [comment]
Thanks for looking into this, nuget restore worked as described :+1:

**Pull request merged**
