### PR TITLE
Support dotnet standard 2.0

### PR DESCRIPTION
**Pull request by mnivet**
This work is based on pull request #67 

The result is a multi-targeted package for net452 and netstandard2.0

Release note of that branch:
* Now support NetStandard2.0 framework
* .Net Framework 4.0 is no more supported, minimal supported version is now .Net Framework 4.5.2
* RestSharp dependency has been upgraded from 105.2.3 to 106.3.1 (**warning:** higher versions are known to be incompatible)
* abstract class `Authenticate` has a new overload for the `GetResponse` method that allow to get a raw string response

other changes are only private or internal changes that goes with the "get a raw string response" re-factoring that has allow to drop need of dynamic objects and a dependency on Microsoft.CSharp package

### CODE REVIEW

**Comment by mnivet** [comment]
@MitjaBezensek I succeed to drop the dependency to Microsoft.CSharp in that branch
but I also observe that the dependency on RestSharp is a bit brittle. It's not linked to that branch but the fact that that branch need to upgrade that dependency will force consumers to upgrade it too, and if they use RestSharp elsewhere in the same code base  they might also be confront to the brittle state of the RestSharp versions...

So I wonder if we should not release a V0.8.0 without that branch, and a V0.9.0 with that branch
We fould be more confortable if we have some consumers that have issues with the upgrade of RestSharp.

So if you are ok with that, I let you merge that branch when you will have release the 0.8.0, and then release the 0.9.0 with that branch

**Comment by MitjaBezensek** [comment]
Sounds good to me. So I can create the 0.8.0 version from the master?

**Comment by mnivet** [comment]
> Sounds good to me. So I can create the 0.8.0 version from the master?

yes !

**Comment by asherber** [comment]
I am curious also about the choices in `RequestExecutor`. The generic constraints on `TRestResponse` are confusing; it would seem to be cleaner to leave everything non-generic, returning `IRestResponse`, and then have `ExecuteRequest<T>` cast `result` to `IRestResponse<T>` before accessing the `Data` property.

**Comment by mnivet** [comment]
> dotnet-xunit

Thanks, I've missed that one when I revert to nunit the branch started by @Tanzy 
It's fixed now

**Comment by mnivet** [comment]
> Tests project should also be multitargeted

I'm used to do that on projects where there is code that depends on the target frameworks, typically when some part of the code are in a `#if NETFRAMEWORK`block or something like that, because I've some code optimisations that depends on the targetframework
And in that case I also add a lot of `#if` directives in the test code to avoid to run twice tests that do not cover something that is coded the same on all target frameworks

On a project like that one where we have done no variations on the code in function of the target framework, multitargetting the tests will double the test executions and I doubt that there is so much issues to found like that...

Have you experimented that elsewhere and found it really valuable ?

**Comment by asherber** [comment]
Regarding tests, I always multitarget the test project when the main assembly is multitargeted. Even if there is no conditional code, it sometimes turns up differences in behavior between runtimes or between other packages that my code depends on.

**Comment by asherber** [comment]
Regarding `RequestExecutor`, the attached works for me. [RequestExecutor.zip](https://github.com/MitjaBezensek/SharpBucket/files/2726947/RequestExecutor.zip)

Remember that `IRestResponse<T>` implements `IRestResponse`. Within the second `ExecuteRequest()` method, we know that the underlying type of `result` at line 21 will be `IRestResponse<T>`, because we are eventually calling `Execute<T>`. So even though the downstream methods are changed to pass around `IRestResponse`, the cast to `IRestResponse<T>` is perfectly safe. But if you wanted to, you could check the cast and throw an exception if it doesn't match.

To me, this makes for cleaner and clearer code.

**Pull request merged**
