### PR TITLE
Added Groups end point for V1

### PR DESCRIPTION
**Pull request by maxwellobi**
Added support for [Bitbucket's Groups API](https://confluence.atlassian.com/bitbucket/groups-endpoint-296093143.html). 

Created V1 testing namespace and made __SharpBucketTests.TestHelpers.cs__ a partial class so that i can have  __TestHelpers.cs__ for V1 OAuth2 Authentication.

All actions on Bitbucket's Groups API has been catered for. Existing structure/convention were adhered.

### CODE REVIEW

**Comment by maxwellobi** [comment]
Hi @MitjaBezensek, can you please take a look at this PR. The build is failing on AppVeyor.  The RestClient is throwing a __System.Reflection.TargetInvocationException__ but the tests pass on my local machine. 

The stacktrace on AppVeyor is 
```
Error : SharBucketTests.V1.EndPoints.GroupsEndPointTests.AddMemberToGroup_ShouldReturnAddedMember
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Net.WebException : REST client encountered an error: Data at the root level is invalid. Line 1, position 1.
  ----> System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SharpBucket.Authentication.Authenticate.GetResponse[T](String url, Method method, T body, IDictionary`2 requestParameters) in C:\projects\sharpbucket\SharpBucket\Authentication\IAuthenticate.cs:line 11
   at SharpBucket.SharpBucket.Send[T](T body, Method method, String overrideUrl, IDictionary`2 requestParameters) in C:\projects\sharpbucket\SharpBucket\SharpBucket.cs:line 94
   at SharpBucket.SharpBucket.Post[T](T body, String overrideUrl) in C:\projects\sharpbucket\SharpBucket\SharpBucket.cs:line 110
   at SharpBucket.V1.EndPoints.GroupsEndPoint.CreateGroup(String name) in C:\projects\sharpbucket\SharpBucket\V1\EndPoints\GroupsEndPoint.cs:line 49
   at SharBucketTests.V1.EndPoints.GroupsEndPointTests.AddMemberToGroup_ShouldReturnAddedMember() in C:\projects\sharpbucket\SharpBucketTests\V1\EndPoints\GroupsEndPointTests.cs:line 42
--WebException
   at SharpBucket.Authentication.RequestExecutor.ExecuteRequest[T](String url, Method method, T body, RestClient client, IDictionary`2 requestParameters) in C:\projects\sharpbucket\SharpBucket\Authentication\RequestExecutor.cs:line 25
--XmlException
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
```
Could this have anything to do with the Bitbucket account on AppVeyor? Any pointers on fixing this?

**Comment by MitjaBezensek** [comment]
Hello @maxwellobi, thanks for your PR.

Yes, it probably has something to do with the appveyor BitBucket account. Maybe permissions issues on the account or something along those lines.

I'll try to look at it during the weekend and let you know what I find out.

**Comment by maxwellobi** [comment]
Thanks @MitjaBezensek , I looked into the exception further. __System.Xml.XmlException__ in the stacktrace gave a clue that RestClient was adding __accept: application/xml__ in the request header. I tried to modify the header directly but it did not work. 

Found a fix on SO - https://stackoverflow.com/questions/22229393/why-is-restsharp-addheaderaccept-application-json-to-a-list-of-item  and applied it. The Exception seems to be resolved, however my tests are still failing because groups are not being created. This could be due to Permission issues on the account as you had suggested.

Let me know when you've looked at it.

**Comment by MitjaBezensek** [comment]
Will do.

**Comment by MitjaBezensek** [comment]
Thanks for the PR and sorry for a late reply 👍 

I updated this PR and fixed the tests. It seems that the API key that is used on AppVeyor didn't have sufficient privileges to create groups. I also refactored the test code a bit.

**Comment by maxwellobi** [comment]
Cool 👍

**Pull request closed without merging**
