### PR TITLE
Added cleaner version for search code feature

### PR DESCRIPTION
**Pull request by mnivet**
This is my response to #122 
The design seems more linq friendly which should improve usability of the feature

I've also fully implemented the POCOs and write unit tests to validate the implementation

### CODE REVIEW

**Comment by starkmsu** [comment]
@mnivet , when can we expect this as a new nuget package version?

**Comment by mnivet** [comment]
@starkmsu I'll work on other improvements till Monday included, then I'll prepare the release.

After that It will depends on @MitjaBezensek availability since it's the only one to have the credentials to push an official version of this package on NuGet.

So if he's not in vacations, you have great chances to get that before the end of next week.

**Comment by MitjaBezensek** [comment]
Just let me know when the release is ready and I'll make the package.

**Comment by starkmsu** [comment]
@mnivet , any updates on new release preparation?

**Comment by MitjaBezensek** [comment]
It's waiting for me, I'll look into it today :)

**Comment by MitjaBezensek** [comment]
Just created the package and uploaded it. It should be available in a few minutes.

**Comment by starkmsu** [comment]
Thanks a lot!

**Pull request merged**
