### PR TITLE
Get next page ID from next link

### LINKED ISSUE #87: IteratePages assumes that next page is sequential
`EndPoint.IteratePages()` assumes that the `page` value in a `next` link will always be an integer that increments by 1. However, https://developer.atlassian.com/bitbucket/api/2/reference/meta/pagination points out that for some collections, the `page` value can be an "unpredictable hash" instead of a sequential number.

I ran into this while retrieving a list of tags.

```csharp
var tags = tagResource.ListTags("myAccount", "myRepo");

// LIBRARY: GET /2.0/repositories/myAccount/myRepo/refs/tags/?pagelen=50
// BITBUCKET: next=https://api.bitbucket.org/2.0/repositories/myAccount/myRepo/refs/tags/?pagelen=50&page=xGCox
// LIBRARY: GET /2.0/repositories/twengg/abs-core/refs/tags/?pagelen=50&page=2
// BITBUCKET: 404 Not Found
```
I can put together a PR to pull the `page` value directly out of the `next` link, instead of just incrementing.

### PR DESCRIPTION
**Pull request by asherber**
Get the next page identifier from the `next` link, instead of just incrementing an `int` counter.

Fixes #87

### CODE REVIEW

**Comment by asherber** [comment]
Not sure why this is failing -- I'll take a look.

**Comment by mnivet** [comment]
I've also take a look and it seems that the `next` link do not always contains a `page` parameter.
here is a sample of what I get in the `next` link: https://api.bitbucket.org/2.0/repositories/?pagelen=50&after=2008-07-31T21%3A17%3A50.817338%2B00%3A00
So it would be better to not try to interpret the next URL, but use it with the less change as possible.

**Comment by asherber** [comment]
Is that URL from `ListPublicRepositories()`? I'll take a look at that workflow.

**Comment by mnivet** [comment]
Writing the IteratePages like that seems to work:
```CSharp
        private IEnumerable<List<TValue>> IteratePages<TValue>(string overrideUrl, int pageLen = DEFAULT_PAGE_LEN, IDictionary<string, object> requestParameters = null)
        {
            Debug.Assert(!String.IsNullOrEmpty(overrideUrl));
            Debug.Assert(!overrideUrl.Contains("?"));

            overrideUrl = overrideUrl.Replace(SharpBucketV2.BITBUCKET_URL, "");

            if (requestParameters == null)
            {
                requestParameters = new Dictionary<string, object>();
            }

            requestParameters["pagelen"] = pageLen;

            IteratorBasedPage<TValue> response;

            do
            {
                response = _sharpBucketV2.Get(new IteratorBasedPage<TValue>(), overrideUrl, requestParameters);
                if (response == null)
                {
                    break;
                }

                yield return response.values;

                if (String.IsNullOrWhiteSpace(response.next))
                {
                    requestParameters = null;
                }
                else
                {
                    var uri = new Uri(response.next);
                    var parsedQuery = HttpUtility.ParseQueryString(uri.Query);
                    requestParameters = parsedQuery.AllKeys.ToDictionary<string, string, object>(key => key, parsedQuery.Get);
                }
            }
            while (requestParameters != null);
        }
```

nb: I removed the local function since it was used only once. The declaration of the local function was breaking the read flow of the method without being able to reduce any code duplication, so it was not really useful here

**Comment by asherber** [comment]
Yes, that's a nice way to do it. 

I'm not crazy about setting `requestParameters` to null just to break out of the loop. What do you think of:

```csharp
do
{
    ...

    if (String.IsNullOrWhitespace(response.next))
        break;
                
    var uri = new Uri(response.next);
    var parsedQuery = HttpUtility.ParseQueryString(uri.Query);
    requestParameters = parsedQuery.AllKeys.ToDictionary<string, string, object>(key => key, parsedQuery.Get);                
}
while (true);
```

**Comment by mnivet** [comment]
I've asked myself if it was a good way to break the loop. So ok for using explicitly the break keyword.
But in that case I think it is more readable to write a `while(true){...}` loop than a `do{...}while(true)` loop, because when you read it you know since the beginning that the exit will be based on a break keyword

**Comment by asherber** [comment]
Another option would be:

```csharp
do
{
    ...

    if (!String.IsNullOrWhiteSpace(response.next))
    { 
        var uri = new Uri(response.next);
        var parsedQuery = HttpUtility.ParseQueryString(uri.Query);
        requestParameters = parsedQuery.AllKeys.ToDictionary<string, string, object>(key => key, parsedQuery.Get);
    }
}
while (!String.IsNullOrWhiteSpace(response.next));
```
What do you think?

**Comment by mnivet** [comment]
I prefer the break. In that last version the response.next is tested twice against IsNullOrWhiteSpace method which is not efficient

**Pull request merged**
