### PR TITLE
Repository creation through v2 api + test case.

### PR DESCRIPTION
**Pull request by jokokko**
A quick implementation for repository creation as I needed it. See if you like it or want to expand on it. I also created a mixin for fluent repository creation configuration. See RepositoriesEndPointMixinsTests.cs:

```csharp
          var repositoryResource = repositoriesEndPoint.CreateRepository(ACCOUNT_NAME, repositoryToCreate, c =>
          {
              c.MakePrivate();
              c.SetLanguage("c#");
              c.SetForkPolicy(ForkWord.NoForks);
          });
```

### CODE REVIEW

**Comment by jokokko** [comment]
Oh and as the tests exercise repository creation (and deletion on cleanup), they require repo admin permissions on the oauth consumer... Thus the failing AppVeyor build.

**Comment by MitjaBezensek** [comment]
Thanks for this PR, I'll take a look at it today or tomorrow. 

One thing I noticed is that you use the standard C# style for curly braces (curly brace in new line). Could you please make it consistent with this projects [style](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/V2/SharpBucketV2.cs#L13). I see that majority of users use the standard C# style, so I'm considering changing to it, so that it will be easier for others to contribute. But at least for now it would be great to keep it consistent with the existing code.

Yeah, I saw the tests. I think I might have only give read permissions to the token that is used on AppVeyor, I'll sort it out.

**Comment by jokokko** [comment]
Created a separate PR that contains formatting changes, but also some additive functionality (no breaking changes). Don't know how much of RestSharp you want to abstract away from endpoints and how much logic should they allow (e.g. should HTTP status code be communicated up to the endpoints).

**Comment by MitjaBezensek** [comment]
I have added the logic to create repositories. 

I saw your fluent api, which looks great, but decided to use the logic that the library uses across other similar calls: create a poco object and pass it to the method that creates the object via the api. I think it's better this way due to consistency and also we don't need to code the fluent code for all the items we wish to add. You can see how it works in the [latest test](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/V2/EndPoints/RepositoryResourceTests.cs#L78).

**Pull request closed without merging**
