### PR TITLE
Added the PutDefaultReviewer Resource

### PR DESCRIPTION
**Pull request by legalchaos**
1. Added a new resource, PutDefaultReviewer, to the repositories endpoint.
2. Added a new test to the test console
3. Updated the coverage documentation

### CODE REVIEW

**Comment by legalchaos** [comment]
It appears a test, ListFollowers_FromTeamAtlassian_ShouldReturnManyFollowers, has failed causing the build to fail. My changes should not have affected this part of the code. I can look into a solution if needed.

**Comment by MitjaBezensek** [comment]
Sorry for a late reply. Yes, the tests are quite brittle. I'll have to rework them, maybe make my own public repository so that the results will stay the same between tests. I'll have some time in the next few days (probably on the weekend) and I'll take a look at this.

Would it be possible to use the style for the braces that I use? I know it's not the default C# style, but for the time being, it would be great if we wouldn't mix the two styles. I'll probably switch back to the default style at some point and just reformat all the code then.

**Comment by legalchaos** [comment]
Didn't even notice that. I'm so used to ReSharper handling my styling for me. I'll revert everything back to that style shortly.

**Comment by legalchaos** [comment]
I fixed the bracket styling issue and the PR is updated.

**Comment by MitjaBezensek** [comment]
Thanks for the PR, it is now merged and the new package is on NuGet!
:+1:

**Pull request merged**
