### PR TITLE
IAsyncEnumerable

### PR DESCRIPTION
**Pull request by mnivet**
Doing a proper async implementation of EnumerateEntity methods require a C#8 feature

This PR probably could not be reintegrate right now (I expect CI to not run with a recent enough version of Visual Studio)

But the important thing to learn from that PR is that adding this feature won't need to add new async methods to the interfaces we expect to expose in #125 
So adding this later won't generate breaking change, so it's not a mandatory thing to do before doing #125

### CODE REVIEW

**Comment by mnivet** [comment]
@MitjaBezensek we need CI to build with VS2019 16.3 or higher to provide that functionality (need support of C#8)
Could you look to upgrade that when you have a bit of free time ?

**Comment by MitjaBezensek** [comment]
I just upgraded the version to VS2019. It doesn't list the exact version, but maybe you try it out and we'll see if it's new enough. There are two other options we can try though:
image

**Comment by j0nimost** [comment]
Have you managed to solve this merge conflict

**Comment by mnivet** [comment]
Not yet. I'll get some time to look at this PR and other things on that repo on this Friday.

**Comment by mnivet** [comment]
Upgrade to VS2019 works fine. Thanks @MitjaBezensek 
The small conflict had been resolved, and code has been fixed.
We are now ready to expose a full async API :)
There is work to do to add overload for all the methods, but recent PR show that the community is ready to help us on that point 👍 
So let's merge that to pursue the full async goal.

**Pull request merged**
