### PR TITLE
Add the support for local bitbucket server.

### PR DESCRIPTION
**Pull request by MitjaBezensek**
This should solve #48. @mongeon maybe you can test this branch on your local installation? You can use the [Program.cs](https://github.com/MitjaBezensek/SharpBucket/blob/master/ConsoleTests/Program.cs) to create a SharpBucket client and connect to your local BitBucket server?

### CODE REVIEW

**Comment by mongeon** [comment]
I'll test it tomorrow and let you know. 

Thanks

**Comment by ffMathy** [comment]
Works fine for me it seems.

**Comment by MitjaBezensek** [comment]
@ffMathy Great, thanks for trying it out. I'm just waiting for BitBucket's response regarding one other issue. I'd like to include that in the next version. But if they don't respond until the weekend I'll make a new version without it.

**Comment by mongeon** [comment]
I've tried it without success. Seems to look to for an account name that I do not have.

**Comment by ffMathy** [comment]
@mongeon could you elaborate? Do you get an exception? What do you specify as your base URL?
And what do you mean by account name?

**Comment by MitjaBezensek** [comment]
I think he's referring to the console program that can be used for testing which requires and account name. If you tested it I'll just merge it and make a new NuGet package. If something won't work we can then go from there.

**Comment by ffMathy** [comment]
@MitjaBezensek this PR is not included in the latest version of the NuGet package. Any ideas why?

**Comment by MitjaBezensek** [comment]
@ffMathy Hm, it should be. Maybe I messed something up 😁I'll take a look when I come from work.

**Comment by MitjaBezensek** [comment]
@ffMathy I pushed another NuGet package. It should be included now. Let me know how it goes 👍

**Pull request merged**
