### PR TITLE
added optional branchortag parameter to ListCommits on commits resource

### PR DESCRIPTION
**Pull request by goncalo-oliveira**
This allows to isolate a branch so that you get only the commits that exist on a single branch, as suggested in Atlassian's documentation,

[GET a commits list for a repository or compare commits across branches](https://confluence.atlassian.com/display/BITBUCKET/commits+or+commit+Resource#commitsorcommitResource-GETacommitslistforarepositoryorcomparecommitsacrossbranches)

### CODE REVIEW

**Comment by MitjaBezensek** [comment]
Thanks for this PR, I just edited the format a bit :)

**Comment by goncalo-oliveira** [comment]
No worries, thanks for starting this project in the first place, it's
really helpful. Any idea when you might release a new build on nuget?

Cheers

On 11 August 2015 at 20:45, Mitja Bezenšek <notifications@github.com> wrote:

> Thanks for this PR, I just edited the format a bit :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MitjaBezensek/SharpBucket/pull/7#issuecomment-130039996>
> .
>



-- 
Gonçalo Oliveira

**Comment by MitjaBezensek** [comment]
I'll try to do it today or tomorrow. I started to work on a solution for the other PR but didn't finish yet. So I'll just include that one in the new release as well.

**Comment by MitjaBezensek** [comment]
I have just released the changes to Nuget. Sorry it took a big longer than expected, though that I can finish another minor feature but ran into some complications so I just dropped the feature and will add it with the next version.

**Pull request merged**
